const places = 
[
    "Nigeria Tofa NG",
    "Slovenia Razvanje SI",
    "Malta Pietà MT",
    "Albania Bradashesh AL",
    "China Huangjia CN",
    "Argentina Arroyo Seco AR",
    "Bangladesh Patiya BD",
    "Indonesia Langgen ID",
    "China Qiaotou CN",
    "Peru Independencia PE",
    "Portugal Canhas PT",
    "China Aizhai CN",
    "Poland Stopnica PL",
    "New Zealand Picton NZ",
    "Thailand Ratchathewi TH",
    "Mexico San Isidro MX",
    "Russia Rodionovo-Nesvetayskaya RU",
    "China Laibin CN",
    "Indonesia Krikil ID",
    "Russia Khvorostyanka RU",
    "Pakistan Bhawāna PK",
    "Indonesia Cikijing ID",
    "Poland Zator PL",
    "France Toulouse FR",
    "Japan Hikari JP",
    "Czech Republic Pyšely CZ",
    "Israel Or Yehuda IL",
    "Central African Republic Kouango CF",
    "Indonesia Pledo ID",
    "China Yanping CN",
    "Philippines Nalus PH",
    "Philippines Cervantes PH",
    "China Kuidou CN",
    "China Tumxuk CN",
    "China Heiheba CN",
    "China Xiangyun CN",
    "Venezuela Masparrito VE",
    "China Shangyuan CN",
    "Philippines Kiloloran PH",
    "China Xiaojin CN",
    "Greece Provatás GR",
    "Greece Skoútari GR",
    "Poland Białaczów PL",
    "China Luobuqiongzi CN",
    "China Ping’an CN",
    "China Dongsheng CN",
    "Argentina El Bolsón AR",
    "Palestinian Territory Zaytā PS",
    "Russia Vostochnyy RU",
    "Indonesia Wangunjaya ID",
    "China Luowan CN",
    "Norway Kristiansand S NO",
    "Iran Kāshmar IR",
    "China Dingjiayao CN",
    "Nicaragua Granada NI",
    "France Nancy FR",
    "China Gaoqiao CN",
    "China Fucheng CN",
    "Antigua and Barbuda Saint John’s AG",
    "Russia Novoaleksandrovsk RU",
    "Sweden Gävle SE",
    "Malta Kerċem MT",
    "Indonesia Magok ID",
    "Sweden Växjö SE",
    "Tanzania Igunga TZ",
    "China Binglincha CN",
    "Indonesia Werangere ID",
    "Poland Łanięta PL",
    "Portugal Pomar PT",
    "United States Santa Cruz US",
    "Russia Churovichi RU",
    "Thailand Phayakkhaphum Phisai TH",
    "China Duofudu CN",
    "Finland Piippola FI",
    "Brazil Ubaitaba BR",
    "Czech Republic Lešná CZ",
    "China Tost CN",
    "Thailand Pak Phanang TH",
    "Ukraine Iza UA",
    "China Dashiju CN",
    "Colombia Malambo CO",
    "China Baitang CN",
    "Poland Trojanów PL",
    "Japan Mito-shi JP",
    "Serbia Doljevac RS",
    "Brazil Barra de São Francisco BR",
    "France Vedène FR",
    "Indonesia Bagangan ID",
    "China Baoxing CN",
    "Nicaragua Telpaneca NI",
    "Portugal Antas PT",
    "Indonesia Sukamulia ID",
    "Kazakhstan Myrzakent KZ",
    "China Jixiang CN",
    "China Huayan CN",
    "China Yangjiaping CN",
    "Chile Puerto Varas CL",
    "Sweden Saltsjöbaden SE",
    "France Boulogne-Billancourt FR",
    "Macedonia Kumanovo MK",
    "Malaysia Kuala Lumpur MY",
    "Thailand Dok Kham Tai TH",
    "China Lidong CN",
    "Indonesia Tanggul Wetan ID",
    "France Lyon FR",
    "China Shuangyuan CN",
    "Ukraine Bilovods'k UA",
    "France Sainte-Luce-sur-Loire FR",
    "Indonesia Pasonobenu ID",
    "China Gaoling CN",
    "China Xinning CN",
    "Philippines Batasan PH",
    "China Sanlicheng CN",
    "Indonesia Mentaras ID",
    "China Jiguan CN",
    "Canada Little Current CA",
    "China Shunde CN",
    "Ukraine Pavlysh UA",
    "Bosnia and Herzegovina Ilići BA",
    "Indonesia Puunage ID",
    "Pakistan Miānwāli PK",
    "Philippines San Juan PH",
    "Indonesia Ciburial ID",
    "Portugal Vale de Açores PT",
    "Portugal Lanhas PT",
    "South Africa Makapanstad ZA",
    "Sweden Ingarö SE",
    "Mongolia Jargalant MN",
    "China Hengdong Chengguanzhen CN",
    "China Zhongbu CN",
    "Venezuela El Real VE",
    "Sweden Helsingborg SE",
    "Tajikistan Dŭstí TJ",
    "China Sangongqiao CN",
    "Poland Kaniów PL",
    "Thailand Phonphisai TH",
    "Uganda Ntungamo UG",
    "Poland Śmiłowo PL",
    "Brazil Rio Claro BR",
    "China Fengshan CN",
    "Philippines Milaor PH",
    "China Xiaoshi CN",
    "Russia Radovitskiy RU",
    "Malawi Lilongwe MW",
    "Belarus Vitebsk BY",
    "Brazil Horizonte BR",
    "Czech Republic Litvínov CZ",
    "China Tongqing CN",
    "Philippines Balud PH",
    "Thailand Sam Phran TH",
    "China Dasongshu CN",
    "China Honglan CN",
    "Croatia Jakšić HR",
    "Croatia Fažana HR",
    "China Xinbu CN",
    "Australia Eastern Suburbs Mc AU",
    "Libya Al Qubbah LY",
    "China Damao CN",
    "Ukraine Bus’k UA",
    "Poland Oksa PL",
    "China Baiyinnuole CN",
    "Portugal Mós PT",
    "Brazil Penalva BR",
    "China Jiuzihe CN",
    "Uruguay Florida UY",
    "Indonesia Sangiang ID",
    "China Wujiaying CN",
    "Czech Republic Jakartovice CZ",
    "United States San Antonio US",
    "Poland Lutomiersk PL",
    "Canada Milton CA",
    "Portugal Antes PT",
    "Vietnam Ô Môn VN",
    "Macedonia Kičevo MK",
    "Indonesia Lobuk ID",
    "Russia Kultayevo RU",
    "France Castelsarrasin FR",
    "Indonesia Oeba ID",
    "United States Phoenix US",
    "Serbia Platičevo RS",
    "China Shache CN",
    "Pakistan Nowshera Cantonment PK",
    "Democratic Republic of the Congo Matadi CD",
    "Indonesia Pulautemiang ID",
    "China Hedi CN",
    "Guatemala Zunilito GT",
    "Portugal Tavira PT",
    "Indonesia Wewoloe ID",
    "China Fenghuo CN",
    "Zimbabwe Bulawayo ZW",
    "Philippines Aglalana PH",
    "France Croix FR",
    "China Yuqunweng CN",
    "Ukraine Nelipyno UA",
    "Germany Dresden DE",
    "Thailand Prakhon Chai TH",
    "Philippines Tumbagaan PH",
    "Haiti Limonade HT",
    "Netherlands Wageningen NL",
    "Sweden Göteborg SE",
    "Rwanda Kigali RW",
    "Indonesia Lonpao Dajah ID",
    "China Tayang CN",
    "Latvia Mārupe LV",
    "Poland Strzelin PL",
    "China Su’ao CN",
    "China Nonghe CN",
    "China Xuji CN",
    "Indonesia Cimuncang ID",
    "Kazakhstan Zyryanovsk KZ",
    "Portugal Lama PT",
    "Brazil Nova Russas BR",
    "Germany München DE",
    "China Zaoxi CN",
    "Indonesia Hadakewa ID",
    "China Gongqiao CN",
    "Mozambique Nampula MZ",
    "Macedonia Sredno Konjare MK",
    "Brazil Ribeirão Preto BR",
    "China Chongqing CN",
    "Argentina Anguil AR",
    "France Paris La Défense FR",
    "Indonesia Manding ID",
    "Brazil Santana de Parnaíba BR",
    "Russia Niny RU",
    "Indonesia Kamubheka ID",
    "Mongolia Bayantal MN",
    "China Shuangxing CN",
    "China Mafang CN",
    "China Changping CN",
    "Canada North Bay CA",
    "Philippines Himaya PH",
    "China Dingbao CN",
    "Japan Sakai-nakajima JP",
    "Indonesia Dawung ID",
    "French Polynesia Taunoa PF",
    "China Licheng CN",
    "Myanmar Taungoo MM",
    "Sweden Ängelholm SE",
    "Portugal Lomba do Loução PT",
    "Indonesia Sukadana Selatan ID",
    "Indonesia Bipolo ID",
    "Russia Cherëmushki RU",
    "France Vitrolles FR",
    "Russia Parfino RU",
    "France Créteil FR",
    "Philippines Kanlagay PH",
    "Philippines Tipo-Tipo PH",
    "China Xiong’erzhai CN",
    "Panama Veracruz PA",
    "Brazil Rio Branco do Sul BR",
    "Russia Vorontsovka RU",
    "Portugal Fonte Boa da Brincosa PT",
    "Greece Kilkís GR",
    "China Liuzuo CN",
    "Malaysia Puchong MY",
    "China Tuanchengshan CN",
    "Albania Pojan AL",
    "Argentina Aviá Terai AR",
    "Iran Qarah Ẕīā’ od Dīn IR",
    "Latvia Bolderaja LV",
    "Indonesia Bata Tengah ID",
    "Indonesia Karipidita ID",
    "Thailand Wang Noi TH",
    "Ireland Loughrea IE",
    "Ireland Stradbally IE",
    "Mongolia Hongor MN",
    "China Shuixi CN",
    "Indonesia Karangtanjung ID",
    "Colombia Pore CO",
    "China Bao’an CN",
    "Canada Saint-Raymond CA",
    "Greece Néa Ankhíalos GR",
    "Afghanistan Anār Darah AF",
    "Palestinian Territory Bardalah PS",
    "Canada Manning CA",
    "France Lavaur FR",
    "China Yunmen CN",
    "France Vendargues FR",
    "China Chenfangji CN",
    "France Alfortville FR",
    "Mauritania Kiffa MR",
    "Indonesia Tumpukrenteng ID",
    "Malaysia Melaka MY",
    "Russia Novopokrovskaya RU",
    "Indonesia Elat ID",
    "Bulgaria Sapareva Banya BG",
    "Bulgaria Blagoevgrad BG",
    "Indonesia Bakunase ID",
    "Philippines Aanislag PH",
    "Indonesia Batakte ID",
    "Indonesia Barapas ID",
    "China Anxiang CN",
    "Democratic Republic of the Congo Bukama CD",
    "Sweden Stockholm SE",
    "Belarus Byahoml’ BY",
    "Portugal Samouco PT",
    "Niger Tibiri NE",
    "Indonesia Gunungsari ID",
    "Kenya Busia KE",
    "Syria Arwād SY",
    "Thailand Sap Yai TH",
    "Armenia Artimet AM",
    "Czech Republic Tupesy CZ",
    "Indonesia Puyung ID",
    "Brazil Mucuri BR",
    "Indonesia Maliiha ID",
    "Russia Svetlyy RU",
    "China Erdaobaihe CN",
    "Portugal Funchal PT",
    "Philippines San Narciso PH",
    "Tajikistan Khŭjand TJ",
    "Czech Republic Jedlová CZ",
    "Afghanistan Mutā Khān AF",
    "El Salvador Intipucá SV",
    "Argentina San Luis AR",
    "Haiti Chambellan HT",
    "Nigeria Ode NG",
    "Indonesia Rancageneng Satu ID",
    "China Matou CN",
    "Indonesia Kombapari ID",
    "Bosnia and Herzegovina Obudovac BA",
    "Portugal Aldeia PT",
    "France Montigny-lès-Metz FR",
    "China Xiadian CN",
    "Yemen Al Jabīn YE",
    "Nepal Ilām NP",
    "Russia Krasnoye RU",
    "Brazil Perdões BR",
    "Russia Boksitogorsk RU",
    "Indonesia Loga ID",
    "Japan Oyama JP",
    "Bermuda Hamilton BM",
    "Mozambique Chokwé MZ",
    "Argentina Molinos AR",
    "South Africa Lichtenburg ZA",
    "Indonesia Sukasirna ID",
    "Cameroon Somié CM",
    "Japan Takahagi JP",
    "Portugal Baleal PT",
    "Madagascar Antananarivo MG",
    "East Timor Maubara TL",
    "Indonesia Nangahale ID",
    "Poland Mrągowo PL",
    "Indonesia Pecatu ID",
    "Brazil Horizonte BR",
    "United States Columbus US",
    "Mexico Miguel Hidalgo MX",
    "Greece Kýria GR",
    "Japan Tomakomai JP",
    "China Caoping CN",
    "Philippines San Fernando PH",
    "United States Macon US",
    "Indonesia Kubangkondanglapangan ID",
    "United States San Rafael US",
    "France Lyon FR",
    "Czech Republic Boskovice CZ",
    "Russia Georgiyevskaya RU",
    "Sweden Vallentuna SE",
    "France Perpignan FR",
    "Sweden Vimmerby SE",
    "Portugal Almada PT",
    "Portugal Vermil PT",
    "Portugal Prior Velho PT",
    "South Korea Cheongju-si KR",
    "Thailand Ratchathewi TH",
    "China Chiguang CN",
    "China Guofu CN",
    "Thailand Chumphon TH",
    "China Huangli CN",
    "China Xingpinglu CN",
    "Argentina Pocito AR",
    "Brazil Barra Velha BR",
    "Syria Akhtarīn SY",
    "Togo Badou TG",
    "Indonesia Singajaya ID",
    "Albania Skore AL",
    "China Wujing CN",
    "Argentina General Manuel J. Campos AR",
    "China Kuzhu CN",
    "United States Pasadena US",
    "China Qixian CN",
    "Russia Ust’-Koksa RU",
    "Thailand Ban Thaen TH",
    "Indonesia Kediren ID",
    "Argentina Zárate AR",
    "El Salvador Nueva Guadalupe SV",
    "Indonesia Bonak ID",
    "Cuba Sagua de Tánamo CU",
    "Czech Republic Plavy CZ",
    "Croatia Podhum HR",
    "China Yanjiatai CN",
    "Indonesia Kemil ID",
    "Uzbekistan Kyzyldzhar UZ",
    "France Plérin FR",
    "China Heichengzi CN",
    "United States Lincoln US",
    "Portugal Quintela PT",
    "China Wuku CN",
    "Canada Bowen Island CA",
    "Poland Chełmża PL",
    "Sudan Bārah SD",
    "Armenia Kotayk’ AM",
    "Nigeria Kujama NG",
    "France Deauville FR",
    "United States Louisville US",
    "Philippines Bantog PH",
    "United States Evansville US",
    "France Chennevières-sur-Marne FR",
    "Argentina Dalmacio Vélez Sársfield AR",
    "Finland Himanka FI",
    "Brazil Novo Hamburgo BR",
    "China Fangshan CN",
    "Philippines Almaguer North PH",
    "Argentina Río Segundo AR",
    "Finland Kouvola FI",
    "South Africa Koppies ZA",
    "Czech Republic Benešov CZ",
    "Pakistan Mehar PK",
    "Ukraine Yasynuvata UA",
    "Mongolia Sergelen MN",
    "Belarus Baruny BY",
    "Estonia Sauga EE",
    "Philippines Bulawin PH",
    "Poland Mikołów PL",
    "China Baishi CN",
    "Poland Zielona Góra PL",
    "Portugal Carregado PT",
    "China Xinjie CN",
    "Philippines Napnapan PH",
    "Iran Kahrīz IR",
    "Poland Sarnaki PL",
    "Kosovo Podujeva XK",
    "China Zhajin CN",
    "Peru Honoria PE",
    "China Fuwen CN",
    "Poland Grzmiąca PL",
    "South Africa Lady Grey ZA",
    "Canada Rocky Mountain House CA",
    "Portugal Sobral PT",
    "Thailand Somdet TH",
    "Serbia Kumane RS",
    "South Korea Nangen KR",
    "Nigeria Nkpor NG",
    "China Qingzhou CN",
    "South Africa Queenstown ZA",
    "Russia Megion RU",
    "Czech Republic Seč CZ",
    "Vietnam Ai Tu VN",
    "Indonesia Selorejo ID",
    "China Liangjing CN",
    "Ghana Ho GH",
    "China Sancha CN",
    "Norway Moss NO",
    "Brazil Imperatriz BR",
    "China Qianchuan CN",
    "South Africa Ndwedwe ZA",
    "Philippines Sabang PH",
    "Colombia Cerinza CO",
    "Philippines San Marcelino PH",
    "Russia Olenegorsk RU",
    "Brazil Itapecerica BR",
    "Poland Sława PL",
    "China Xiangcheng CN",
    "Russia Ulety RU",
    "China Hexi CN",
    "Indonesia Pasirgaru ID",
    "Indonesia Krajan Kulon ID",
    "Kenya Nakuru KE",
    "Tanzania Muheza TZ",
    "Philippines Banawang PH",
    "Madagascar Ampanihy MG",
    "Indonesia Banjar Gunungpande ID",
    "Czech Republic Rokycany CZ",
    "China Shanling CN",
    "Portugal Barra Cheia PT",
    "China Huafeng CN",
    "Indonesia Kerek ID",
    "China Zongjia CN",
    "Philippines Pulo PH",
    "Philippines Luna PH",
    "China Hongcheng CN",
    "Greece Ouranoupolis GR",
    "Philippines Carpenter PH",
    "China Qingliu CN",
    "Canada Lloydminster CA",
    "China Dongxing CN",
    "China Xinfa CN",
    "Canada Sylvan Lake CA",
    "France Nevers FR",
    "Sweden Göteborg SE",
    "France Mantes-la-Jolie FR",
    "Canada Antigonish CA",
    "Ethiopia Asaita ET",
    "Colombia Cali CO",
    "France Bègles FR",
    "Portugal Valejas PT",
    "Russia Trudobelikovskiy RU",
    "China Zhijiang CN",
    "China Shuangtang CN",
    "Ivory Coast Bouaké CI",
    "China Hexi CN",
    "Russia Svetlograd RU",
    "Greece Kampánis GR",
    "Russia Polyarnyy RU",
    "Dominican Republic Pedro Sánchez DO",
    "Norway Oslo NO",
    "Tunisia Banbalah TN",
    "China Xiangshi CN",
    "China Chengbei CN",
    "Canada Magrath CA",
    "Russia El’brus RU",
    "China Zhongcheng CN",
    "Germany Hamburg Winterhude DE",
    "Vietnam Mỏ Cày VN",
    "China Dawusu CN",
    "China Tajike’abati CN",
    "Latvia Daugavpils LV",
    "Mauritius Mahébourg MU",
    "Finland Kuhmalahti FI",
    "Brazil Barão de Melgaço BR",
    "Cuba Nueva Gerona CU",
    "Russia Tuapse RU",
    "United States Reno US",
    "Philippines Labrador PH",
    "Pakistan Zafarwāl PK",
    "Turkmenistan Türkmenabat TM",
    "China Jiaodai CN",
    "Indonesia Karanglincak ID",
    "China Changzheng CN",
    "Cameroon Mora CM",
    "Ecuador Azogues EC",
    "China Wentugaole CN",
    "United States Sacramento US",
    "Bosnia and Herzegovina Rumboci BA",
    "Myanmar Kanbe MM",
    "China Xi’an CN",
    "France Paris 07 FR",
    "China Shima CN",
    "Palestinian Territory Ūdalah PS",
    "China Xidoupu CN",
    "Russia Tuymazy RU",
    "Colombia Chinú CO",
    "Russia Psyzh RU",
    "Uganda Kasese UG",
    "Czech Republic Fryčovice CZ",
    "Czech Republic Vrbovec CZ",
    "China Wansheng CN",
    "Philippines Pinaring PH",
    "France Grenoble FR",
    "Brazil Manhumirim BR",
    "Poland Sieradza PL",
    "Colombia San Benito Abad CO",
    "Azerbaijan Buzovna AZ",
    "China Shangjing CN",
    "Brazil Vilhena BR",
    "Slovenia Hrib-Loški Potok SI",
    "Philippines Concepcion PH",
    "Indonesia Oebobo ID",
    "Russia Fryazino RU",
    "Egypt Sīdī Sālim EG",
    "Japan Mihara JP",
    "Cuba Fomento CU",
    "Poland Zabierzów PL",
    "Indonesia Basiong ID",
    "China Jugezhuang CN",
    "Estonia Hullo EE",
    "Russia Surovikino RU",
    "China Geshan CN",
    "Philippines Alegria PH",
    "Ukraine Lyubymivka UA",
    "Argentina Lanús AR",
    "France Paris 15 FR",
    "Mexico Vicente Guerrero MX",
    "Indonesia Sukaharja ID",
    "Brazil Santo Amaro da Imperatriz BR",
    "Russia Sinyavino RU",
    "China Hutou CN",
    "Brazil Barreiras BR",
    "Portugal Santarém PT",
    "Indonesia Tohong ID",
    "Philippines San Luis PH",
    "Sweden Kinna SE",
    "Somalia Laascaanood SO",
    "Portugal Ourozinho PT",
    "Peru Cahuac PE",
    "Yemen Al Bāţinah YE",
    "France Dunkerque FR",
    "France Avignon FR",
    "Germany Karlsruhe DE",
    "Poland Józefów PL",
    "China Matoupu CN",
    "Japan Shiogama JP",
    "China Laojunmiao CN",
    "Poland Końskowola PL",
    "Greece Dimitsána GR",
    "Indonesia Birayang ID",
    "China Simenqian CN",
    "Argentina Elena AR",
    "Poland Ośno Lubuskie PL",
]


const generateFrom = (i) => places[randomInt(0, places.length)];

const generateTo = (i) => places[randomInt(0, places.length)];


const generateLocation = i => 
    new Location(
        generateFrom(i),
        generateTo(i),
    );


const generateLocations = createArray(generateLocation(20));
